version: '3.8'

services:
  mongo:
    hostname: mongo
    image: mongo:7.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hsa103
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=hsa103
    restart: always
    networks:
      - gateway

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    networks:
      - gateway
    restart: always

  node-app:
    hostname: node-app
    build: ./node_app
    networks:
      - gateway   
    restart: always
    depends_on:
      - mongo
      - elasticsearch

  hsa310-nginx:
    hostname: hsa310-nginx
    image: nginx:alpine3.18
    ports: 
      - 8098:80  
    links: 
      - node-app
    depends_on: 
      - node-app
      - mongo
      - elasticsearch
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    networks:
      - gateway

  influxdb:
    hostname: influxdb
    image: influxdb:1.8.10-alpine
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminadmin
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb    
    networks:
      - gateway

  grafana:
    hostname: grafana
    image: grafana/grafana:10.2.0
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - gateway

  telegraf:
    hostname: telegraf
    image: telegraf:1.28.3-alpine
    entrypoint: /bin/sh -c "chmod 666 /var/run/docker.sock && /entrypoint.sh telegraf"
    environment:
      - HOST_NAME=telegraf
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - DATABASE=influx
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - elasticsearch
      - grafana
      - node-app
      - hsa310-nginx
      - mongo
    links:
      - influxdb
    networks:
      - gateway

  ab:
    hostname: ab
    build: ./ab  
    restart: always
    depends_on:
      - node-app
      - hsa310-nginx
    networks:
      - gateway 
    
networks:
  gateway: {}

volumes:
  grafana_data: {}
  influxdb_data: {}